initdata();

function initdata() {
  // USERS
  if (!localStorage.users) {
    const users = [
      {
        id: 1,
        name: "Alice",
        email: "alice@teste.com",
        password: "alice1234",
        isAdmin: false,
        homeAirport: "OPO",
        miles: {
          available: 236,
          total: 4300,
        },
        trips: [1],
        badges: ["us", "fr", "jp", "de"],
        favorites: ["Porto", "Barcelona"],
      },
      {
        id: 2,
        name: "Bob",
        email: "bob@teste.com",
        password: "bob1234",
        isAdmin: true,
        homeAirport: "LAX",
        miles: {
          available: 465,
          total: 2020,
        },
        trips: [2],
        badges: ["br", "pt", "es"],
        favorites: ["Rio Grande do Sul", "Cidade do México", "Roménia"],
      },
      {
        id: 3,
        name: "Charlie",
        email: "charlie@teste.com",
        password: "charlie1234",
        isAdmin: false,
        homeAirport: "LIS",
        miles: {
          available: 200,
          total: 1300,
        },
        trips: [1, 2],
        badges: ["it", "ca", "mx", "nl"],
        favorites: ["Nova Iorque", "Las Vegas"],
      },
      {
        id: 4,
        name: "teste",
        email: "boba@teste.com",
        password: "123",
        isAdmin: false,
        homeAirport: "SFO",
        miles: {
          available: 10,
          total: 1240,
        },
        trips: [2],
        badges: ["au", "ch", "se"],
        favorites: ["Andorra", "Madrid"],
      },
    ];
    console.log("Injecting Data");
    localStorage.setItem("users", JSON.stringify(users));
  }

  // TOURISM TYPE
  if (!localStorage.tourismTypes) {
    const tourismTypes = [
      { id: 1, name: "Aventura" },
      { id: 2, name: "Praia" },
      { id: 3, name: "Religioso" },
      { id: 4, name: "Gastronómico" },
    ];
    localStorage.setItem("tourismTypes", JSON.stringify(tourismTypes));
    console.log("Tourism types initialized");
  }

  // FLIGHTS
  if (!localStorage.flights) {
    const flights = [
      {
        id: 1,
        origin: "OPO",
        destination: "LIS",
        destinationName: "Lisboa",
        departureTime: "2025-07-01T08:00",
        arrivalTime: "2025-07-01T09:00",
        price: 80,
        duration: "1h",
        company: "TAP",
        distance: 194.5,
        destinLat: 38.7,
        destinLong: -9.1,
        poi: [
          {
            name: "Torre de Belém",
            latitude: 38.7,
            long: -9.2,
            tourismTypes: [2, 4],
          },
          {
            name: "Mosteiro dos Jerónimos",
            latitude: 38.7,
            long: -9.2,
            tourismTypes: [3],
          },
        ],
      },
      {
        id: 2,
        origin: "OPO",
        destination: "BCN",
        destinationName: "Barcelona",
        departureTime: "2025-07-02T09:00",
        arrivalTime: "2025-07-02T11:00",
        price: 120,
        duration: "2h",
        company: "Vueling",
        distance: 625.1,
        destinLat: 41.4,
        destinLong: 2.2,
        poi: [
          {
            name: "Sagrada Família",
            latitude: 41.4,
            long: 2.2,
            tourismTypes: [3],
          },
          {
            name: "Praia de Barceloneta",
            latitude: 41.4,
            long: 2.2,
            tourismTypes: [2],
          },
        ],
      },
      {
        id: 3,
        origin: "OPO",
        destination: "MAD",
        destinationName: "Madrid",
        departureTime: "2025-07-03T07:30",
        arrivalTime: "2025-07-03T09:00",
        price: 90,
        duration: "1h 30m",
        company: "Iberia",
        distance: 273.4,
        destinLat: 40.4,
        destinLong: -3.7,
        poi: [
          {
            name: "Museo del Prado",
            latitude: 40.4,
            long: -3.7,
            tourismTypes: [4],
          },
          {
            name: "Palacio Real",
            latitude: 40.4,
            long: -3.7,
            tourismTypes: [1, 3],
          },
        ],
      },
      {
        id: 4,
        origin: "OPO",
        destination: "CDG",
        destinationName: "Paris",
        departureTime: "2025-07-04T10:00",
        arrivalTime: "2025-07-04T13:00",
        price: 150,
        duration: "3h",
        company: "Air France",
        distance: 741.3,
        destinLat: 48.9,
        destinLong: 2.4,
        poi: [
          {
            name: "Torre Eiffel",
            latitude: 48.9,
            long: 2.3,
            tourismTypes: [1],
          },
          {
            name: "Museu do Louvre",
            latitude: 48.9,
            long: 2.3,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 5,
        origin: "OPO",
        destination: "LHR",
        destinationName: "Londres",
        departureTime: "2025-07-05T11:00",
        arrivalTime: "2025-07-05T13:00",
        price: 180,
        duration: "2h",
        company: "British Airways",
        distance: 834.9,
        destinLat: 51.5,
        destinLong: -0.1,
        poi: [
          { name: "Big Ben", latitude: 51.5, long: -0.1, tourismTypes: [3] },
          { name: "Hyde Park", latitude: 51.5, long: -0.1, tourismTypes: [1] },
        ],
      },
      {
        id: 6,
        origin: "OPO",
        destination: "FRA",
        destinationName: "Frankfurt",
        departureTime: "2025-07-06T12:00",
        arrivalTime: "2025-07-06T15:00",
        price: 210,
        duration: "3h",
        company: "Lufthansa",
        distance: 1015.1,
        destinLat: 50.1,
        destinLong: 8.6,
        poi: [
          { name: "Römerberg", latitude: 50.1, long: 8.6, tourismTypes: [4] },
          { name: "Main Tower", latitude: 50.1, long: 8.6, tourismTypes: [1] },
        ],
      },
      {
        id: 7,
        origin: "OPO",
        destination: "MXP",
        destinationName: "Milão",
        departureTime: "2025-07-07T14:00",
        arrivalTime: "2025-07-07T16:30",
        price: 200,
        duration: "2h 30m",
        company: "Ryanair",
        distance: 941.0,
        destinLat: 45.5,
        destinLong: 9.2,
        poi: [
          {
            name: "Duomo di Milano",
            latitude: 45.5,
            long: 9.2,
            tourismTypes: [3],
          },
          {
            name: "Galleria Vittorio Emanuele",
            latitude: 45.5,
            long: 9.2,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 8,
        origin: "OPO",
        destination: "AMS",
        destinationName: "Amsterdão",
        departureTime: "2025-07-08T07:00",
        arrivalTime: "2025-07-08T10:00",
        price: 220,
        duration: "3h",
        company: "KLM",
        distance: 978.3,
        destinLat: 52.4,
        destinLong: 4.9,
        poi: [
          {
            name: "Museu Van Gogh",
            latitude: 52.4,
            long: 4.9,
            tourismTypes: [4],
          },
          { name: "Canal Belt", latitude: 52.4, long: 4.9, tourismTypes: [2] },
        ],
      },
      {
        id: 9,
        origin: "OPO",
        destination: "ZRH",
        destinationName: "Zurique",
        departureTime: "2025-07-09T13:00",
        arrivalTime: "2025-07-09T16:00",
        price: 250,
        duration: "3h",
        company: "Swiss",
        distance: 952.0,
        destinLat: 47.4,
        destinLong: 8.5,
        poi: [
          { name: "Old Town", latitude: 47.4, long: 8.5, tourismTypes: [1] },
          { name: "Lake Zurich", latitude: 47.4, long: 8.5, tourismTypes: [2] },
        ],
      },
      {
        id: 10,
        origin: "OPO",
        destination: "VIE",
        destinationName: "Viena",
        departureTime: "2025-07-10T06:30",
        arrivalTime: "2025-07-10T09:30",
        price: 270,
        duration: "3h",
        company: "Austrian Airlines",
        distance: 1202.4,
        destinLat: 48.2,
        destinLong: 16.4,
        poi: [
          {
            name: "Palácio de Schönbrunn",
            latitude: 48.2,
            long: 16.4,
            tourismTypes: [3],
          },
          {
            name: "Stephansplatz",
            latitude: 48.2,
            long: 16.4,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 11,
        origin: "OPO",
        destination: "CPH",
        destinationName: "Copenhaga",
        departureTime: "2025-07-11T12:00",
        arrivalTime: "2025-07-11T15:00",
        price: 300,
        duration: "3h",
        company: "SAS",
        distance: 1408.2,
        destinLat: 55.7,
        destinLong: 12.6,
        poi: [
          { name: "Nyhavn", latitude: 55.7, long: 12.6, tourismTypes: [2] },
          {
            name: "Palácio de Amalienborg",
            latitude: 55.7,
            long: 12.6,
            tourismTypes: [3],
          },
        ],
      },
      {
        id: 12,
        origin: "OPO",
        destination: "OSL",
        destinationName: "Oslo",
        departureTime: "2025-07-12T09:00",
        arrivalTime: "2025-07-12T12:00",
        price: 320,
        duration: "3h",
        company: "Norwegian",
        distance: 1482.9,
        destinLat: 59.9,
        destinLong: 10.7,
        poi: [
          {
            name: "Vigeland Park",
            latitude: 59.9,
            long: 10.7,
            tourismTypes: [1],
          },
          {
            name: "Museu dos Barcos Vikings",
            latitude: 59.9,
            long: 10.7,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 13,
        origin: "OPO",
        destination: "DUB",
        destinationName: "Dublin",
        departureTime: "2025-07-13T07:00",
        arrivalTime: "2025-07-13T09:30",
        price: 230,
        duration: "2h 30m",
        company: "Aer Lingus",
        distance: 869.6,
        destinLat: 53.3,
        destinLong: -6.2,
        poi: [
          {
            name: "Guinness Storehouse",
            latitude: 53.3,
            long: -6.2,
            tourismTypes: [4],
          },
          {
            name: "Trinity College",
            latitude: 53.3,
            long: -6.2,
            tourismTypes: [3],
          },
        ],
      },
      {
        id: 14,
        origin: "OPO",
        destination: "ATH",
        destinationName: "Atenas",
        departureTime: "2025-07-14T11:00",
        arrivalTime: "2025-07-14T16:00",
        price: 360,
        duration: "4h",
        company: "Aegean Airlines",
        distance: 1773.5,
        destinLat: 37.9,
        destinLong: 23.7,
        poi: [
          { name: "Acrópole", latitude: 37.9, long: 23.7, tourismTypes: [3] },
          { name: "Plaka", latitude: 37.9, long: 23.7, tourismTypes: [4] },
        ],
      },
      {
        id: 15,
        origin: "OPO",
        destination: "IST",
        destinationName: "Istambul",
        departureTime: "2025-07-15T10:00",
        arrivalTime: "2025-07-15T15:00",
        price: 400,
        duration: "4h",
        company: "Turkish Airlines",
        distance: 1795.0,
        destinLat: 41.0,
        destinLong: 28.9,
        poi: [
          {
            name: "Hagia Sophia",
            latitude: 41.0,
            long: 28.9,
            tourismTypes: [3],
          },
          {
            name: "Grand Bazaar",
            latitude: 41.0,
            long: 28.9,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 16,
        origin: "OPO",
        destination: "BRU",
        destinationName: "Bruxelas",
        departureTime: "2025-07-16T08:30",
        arrivalTime: "2025-07-16T11:00",
        price: 200,
        duration: "2h 30m",
        company: "Brussels Airlines",
        distance: 833.0,
        destinLat: 50.8,
        destinLong: 4.4,
        poi: [
          { name: "Grand Place", latitude: 50.8, long: 4.4, tourismTypes: [1] },
          { name: "Atomium", latitude: 50.8, long: 4.4, tourismTypes: [4] },
        ],
      },
      {
        id: 17,
        origin: "OPO",
        destination: "PRG",
        destinationName: "Praga",
        departureTime: "2025-07-17T09:00",
        arrivalTime: "2025-07-17T12:00",
        price: 280,
        duration: "3h",
        company: "Czech Airlines",
        distance: 1103.6,
        destinLat: 50.1,
        destinLong: 14.4,
        poi: [
          {
            name: "Castelo de Praga",
            latitude: 50.1,
            long: 14.4,
            tourismTypes: [3],
          },
          {
            name: "Ponte Carlos",
            latitude: 50.1,
            long: 14.4,
            tourismTypes: [1],
          },
        ],
      },
      {
        id: 18,
        origin: "OPO",
        destination: "HEL",
        destinationName: "Helsínquia",
        departureTime: "2025-07-18T10:00",
        arrivalTime: "2025-07-18T15:00",
        price: 410,
        duration: "4h",
        company: "Finnair",
        distance: 1830.4,
        destinLat: 60.2,
        destinLong: 24.9,
        poi: [
          {
            name: "Fortaleza de Suomenlinna",
            latitude: 60.2,
            long: 24.9,
            tourismTypes: [1],
          },
          {
            name: "Catedral de Helsínquia",
            latitude: 60.2,
            long: 24.9,
            tourismTypes: [3],
          },
        ],
      },
      {
        id: 19,
        origin: "OPO",
        destination: "ROM",
        destinationName: "Roma",
        departureTime: "2025-07-19T13:00",
        arrivalTime: "2025-07-19T16:00",
        price: 260,
        duration: "3h",
        company: "ITA Airways",
        distance: 1056.9,
        destinLat: 41.9,
        destinLong: 12.5,
        poi: [
          { name: "Coliseu", latitude: 41.9, long: 12.5, tourismTypes: [3] },
          {
            name: "Fontana di Trevi",
            latitude: 41.9,
            long: 12.5,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 20,
        origin: "OPO",
        destination: "REK",
        destinationName: "Reiquiavique",
        departureTime: "2025-07-20T14:00",
        arrivalTime: "2025-07-20T18:00",
        price: 450,
        duration: "4h",
        company: "Icelandair",
        distance: 1598.1,
        destinLat: 64.1,
        destinLong: -21.9,
        poi: [
          {
            name: "Hallgrímskirkja",
            latitude: 64.1,
            long: -21.9,
            tourismTypes: [3],
          },
          {
            name: "Blue Lagoon",
            latitude: 64.1,
            long: -21.9,
            tourismTypes: [2],
          },
        ],
      },
      {
        id: 21,
        origin: "LIS",
        destination: "MAD",
        destinationName: "Madrid",
        departureTime: "2025-07-21T09:00",
        arrivalTime: "2025-07-21T10:30",
        price: 70,
        duration: "1h 30m",
        company: "Iberia",
        distance: 313.5,
        destinLat: 40.4,
        destinLong: -3.7,
        poi: [
          {
            name: "Museo del Prado",
            latitude: 40.4,
            long: -3.7,
            tourismTypes: [4],
          },
          {
            name: "Palacio Real",
            latitude: 40.4,
            long: -3.7,
            tourismTypes: [1, 3],
          },
        ],
      },
      {
        id: 22,
        origin: "MAD",
        destination: "ROM",
        destinationName: "Roma",
        departureTime: "2025-07-22T12:00",
        arrivalTime: "2025-07-22T14:30",
        price: 150,
        duration: "2h 30m",
        company: "ITA Airways",
        distance: 848.2,
        destinLat: 41.9,
        destinLong: 12.5,
        poi: [
          { name: "Coliseu", latitude: 41.9, long: 12.5, tourismTypes: [3] },
          {
            name: "Fontana di Trevi",
            latitude: 41.9,
            long: 12.5,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 23,
        origin: "ROM",
        destination: "ATH",
        destinationName: "Atenas",
        departureTime: "2025-07-23T15:00",
        arrivalTime: "2025-07-23T18:30",
        price: 180,
        duration: "2h 30m",
        company: "Aegean Airlines",
        distance: 653.9,
        destinLat: 37.9,
        destinLong: 23.7,
        poi: [
          { name: "Acrópole", latitude: 37.9, long: 23.7, tourismTypes: [3] },
          { name: "Plaka", latitude: 37.9, long: 23.7, tourismTypes: [4] },
        ],
      },
      {
        id: 24,
        origin: "BCN",
        destination: "CDG",
        destinationName: "Paris",
        departureTime: "2025-07-24T08:30",
        arrivalTime: "2025-07-24T10:30",
        price: 130,
        duration: "2h",
        company: "Vueling",
        distance: 515.6,
        destinLat: 48.9,
        destinLong: 2.4,
        poi: [
          {
            name: "Torre Eiffel",
            latitude: 48.9,
            long: 2.3,
            tourismTypes: [1],
          },
          {
            name: "Museu do Louvre",
            latitude: 48.9,
            long: 2.3,
            tourismTypes: [4],
          },
        ],
      },
      {
        id: 25,
        origin: "CDG",
        destination: "LHR",
        destinationName: "Londres",
        departureTime: "2025-07-25T14:00",
        arrivalTime: "2025-07-25T14:50",
        price: 110,
        duration: "1h",
        company: "British Airways",
        distance: 214.8,
        destinLat: 51.5,
        destinLong: -0.1,
        poi: [
          { name: "Big Ben", latitude: 51.5, long: -0.1, tourismTypes: [3] },
          { name: "Hyde Park", latitude: 51.5, long: -0.1, tourismTypes: [1] },
        ],
      },
      {
        id: 26,
        origin: "LHR",
        destination: "AMS",
        destinationName: "Amsterdão",
        departureTime: "2025-07-26T10:00",
        arrivalTime: "2025-07-26T12:20",
        price: 140,
        duration: "1h 20m",
        company: "KLM",
        distance: 230.7,
        destinLat: 52.4,
        destinLong: 4.9,
        poi: [
          {
            name: "Museu Van Gogh",
            latitude: 52.4,
            long: 4.9,
            tourismTypes: [4],
          },
          { name: "Canal Belt", latitude: 52.4, long: 4.9, tourismTypes: [2] },
        ],
      },
      {
        id: 27,
        origin: "AMS",
        destination: "FRA",
        destinationName: "Frankfurt",
        departureTime: "2025-07-27T09:00",
        arrivalTime: "2025-07-27T10:30",
        price: 100,
        duration: "1h 30m",
        company: "Lufthansa",
        distance: 226.3,
        destinLat: 50.1,
        destinLong: 8.6,
        poi: [
          { name: "Römerberg", latitude: 50.1, long: 8.6, tourismTypes: [4] },
          { name: "Main Tower", latitude: 50.1, long: 8.6, tourismTypes: [1] },
        ],
      },
      {
        id: 28,
        origin: "FRA",
        destination: "ZRH",
        destinationName: "Zurique",
        departureTime: "2025-07-28T13:00",
        arrivalTime: "2025-07-28T14:30",
        price: 120,
        duration: "1h 30m",
        company: "Swiss",
        distance: 179.4,
        destinLat: 47.4,
        destinLong: 8.5,
        poi: [
          { name: "Old Town", latitude: 47.4, long: 8.5, tourismTypes: [1] },
          { name: "Lake Zurich", latitude: 47.4, long: 8.5, tourismTypes: [2] },
        ],
      },
    ];

    localStorage.setItem("flights", JSON.stringify(flights));
    console.log("Flights initialized");
  }

  // TRIPS
  if (!localStorage.trips) {
    const trips = [
      {
        id: 1,
        name: "Férias em Barcelona",
        typesOfTourism: [2, 4],
        origin: "OPO",
        destination: "BCN",
        price: 500,
        company: "TAP",
        duration: "7 dias",
        startDate: "2025-06-05",
        endDate: "2025-06-12",
        description: "Descubra as praias e a gastronomia de Barcelona.",
        isPack: true,
        flights: [2],
      },
      {
        id: 2,
        name: "Tour pelos EUA",
        typesOfTourism: [1, 4],
        origin: "LAX",
        destination: "JFK",
        price: 1200,
        company: "Delta",
        duration: "10 dias",
        startDate: "2025-07-01",
        endDate: "2025-07-11",
        description: "Viagem pelas principais cidades americanas.",
        isPack: false,
        flights: [3],
      },
      {
        id: 2,
        name: "Semana na Suíça",
        typesOfTourism: [1, 4],
        origin: "OPO",
        destination: "ZRH",
        price: 300,
        company: "Swiss Air",
        duration: "7 dias",
        startDate: "2025-07-01",
        endDate: "2025-07-11",
        description: "Descubra as montanhas.",
        isPack: true,
        flights: [2],
      },
      {
        id: 3,
        name: "Visita ao Iceberg",
        typesOfTourism: [1, 4],
        origin: "OPO",
        destination: "ICE",
        price: 3200,
        company: "Icelandair",
        duration: "10 dias",
        startDate: "2025-07-01",
        endDate: "2025-07-11",
        description: "Descubra a Islândia.",
        isPack: true,
        flights: [1],
      },
    ];
    localStorage.setItem("trips", JSON.stringify(trips));
    console.log("Trips initialized");
  }
}
