initdata();

function initdata() {
  // USERS
  if (!localStorage.users) {
    const users = [
      {
        id: 1,
        name: "Alice",
        email: "alice@teste.com",
        password: "Iv2mJg5C99wWDBEFHvktDKSlnqcV8x5ldNtBbkFR/gU=",
        isAdmin: false,
        homeAirport: "OPO",
        miles: {
          available: 236,
          total: 4300,
        },
        trips: [1],
        badges: ["us", "fr", "jp", "de"],
        favorites: ["Porto", "Barcelona"],
        lastScratch: "2025-04-08",
      },
      {
        id: 2,
        name: "Bob",
        email: "bob@teste.com",
        password: "doj2kmjCoFbaRTTgL17Qm6h9BvhI9krOnzlF7O9tRXc=",
        isAdmin: true,
        homeAirport: "LAX",
        miles: {
          available: 465,
          total: 2020,
        },
        trips: [2],
        badges: ["br", "pt", "es"],
        favorites: ["Rio Grande do Sul", "Cidade do México", "Roménia"],
        lastScratch: "2025-06-04",
      },
      {
        id: 3,
        name: "Charlie",
        email: "charlie@teste.com",
        password: "T1seFreOPCHSRHhB/+briZwYHvkvnNuAZzzcnZCUIfM=",
        isAdmin: false,
        homeAirport: "LIS",
        miles: {
          available: 200,
          total: 1300,
        },
        trips: [1, 2],
        badges: ["it", "ca", "mx", "nl"],
        favorites: ["Nova Iorque", "Las Vegas"],
        lastScratch: "2025-06-04",
      },
      {
        id: 4,
        name: "teste",
        email: "boba@teste.com",
        password: "JPjElV6dkZO6hqE9ccWLJqJ1UXqbTl+WjlWH7x9uS9Q=",
        isAdmin: false,
        homeAirport: "SFO",
        miles: {
          available: 10,
          total: 1240,
        },
        trips: [2],
        badges: ["au", "ch", "se"],
        favorites: ["Andorra", "Madrid"],
        lastScratch: "2025-06-08",
      },
    ];
    console.log("Injecting Data");
    localStorage.setItem("users", JSON.stringify(users));
  }

  // TOURISM TYPE
  if (!localStorage.tourismTypes) {
    const tourismTypes = [
      { id: 1, name: "Aventura" },
      { id: 2, name: "Praia" },
      { id: 3, name: "Religioso" },
      { id: 4, name: "Gastronómico" },
    ];
    localStorage.setItem("tourismTypes", JSON.stringify(tourismTypes));
    console.log("Tourism types initialized");
  }

  // FLIGHTS
  if (!localStorage.flights) {
    const flights = [
      {
        id: 1,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "LIS",
        destinationName: "Lisboa",
        destinationLat: 38.7,
        destinationLong: -9.1,
        departureTime: "2025-07-01T08:00",
        arrivalTime: "2025-07-01T09:00",
        price: 60,
        duration: 60,
        company: "TAP",
        distance: 313,
        tourismTypes: [1, 2],
        poi: [],
        badge: "pt",
      },
      {
        id: 2,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "MAD",
        destinationName: "Madrid",
        destinationLat: 40.4,
        destinationLong: -3.7,
        departureTime: "2025-07-02T12:00",
        arrivalTime: "2025-07-02T14:00",
        price: 80,
        duration: 120,
        company: "Iberia",
        distance: 438,
        tourismTypes: [1, 3],
        poi: [],
        badge: "es",
      },
      {
        id: 3,
        origin: "LIS",
        originName: "Lisboa",
        originLat: 38.7,
        originLong: -9.1,
        destination: "BCN",
        destinationName: "Barcelona",
        destinationLat: 41.4,
        destinationLong: 2.2,
        departureTime: "2025-07-03T13:00",
        arrivalTime: "2025-07-03T15:00",
        price: 90,
        duration: 120,
        company: "Vueling",
        distance: 1006,
        tourismTypes: [2, 3],
        poi: [],
        badge: "pt",
      },
      {
        id: 4,
        origin: "MAD",
        originName: "Madrid",
        originLat: 40.4,
        originLong: -3.7,
        destination: "PAR",
        destinationName: "Paris",
        destinationLat: 48.8,
        destinationLong: 2.3,
        departureTime: "2025-07-04T17:00",
        arrivalTime: "2025-07-04T19:00",
        price: 100,
        duration: 120,
        company: "Air France",
        distance: 1052,
        tourismTypes: [1, 4],
        poi: [],
        badge: "fr",
      },
      {
        id: 5,
        origin: "BCN",
        originName: "Barcelona",
        originLat: 41.4,
        originLong: 2.2,
        destination: "ROM",
        destinationName: "Roma",
        destinationLat: 41.9,
        destinationLong: 12.5,
        departureTime: "2025-07-05T18:00",
        arrivalTime: "2025-07-05T20:00",
        price: 110,
        duration: 120,
        company: "ITA Airways",
        distance: 859,
        tourismTypes: [2, 5],
        poi: [],
        badge: "es",
      },
      {
        id: 6,
        origin: "ROM",
        originName: "Roma",
        originLat: 41.9,
        originLong: 12.5,
        destination: "ATH",
        destinationName: "Atenas",
        destinationLat: 37.9,
        destinationLong: 23.7,
        departureTime: "2025-07-07T09:00",
        arrivalTime: "2025-07-07T12:00",
        price: 120,
        duration: 180,
        company: "Aegean",
        distance: 1050,
        tourismTypes: [2, 6],
        poi: [],
        badge: "it",
      },
      {
        id: 7,
        origin: "ATH",
        originName: "Atenas",
        originLat: 37.9,
        originLong: 23.7,
        destination: "IST",
        destinationName: "Istanbul",
        destinationLat: 41.0,
        destinationLong: 28.9,
        departureTime: "2025-07-09T14:00",
        arrivalTime: "2025-07-09T16:00",
        price: 130,
        duration: 120,
        company: "Turkish Airlines",
        distance: 563,
        tourismTypes: [6, 7],
        poi: [],
        badge: "tr",
      },

      {
        id: 8,
        origin: "PAR",
        originName: "Paris",
        originLat: 48.8,
        originLong: 2.3,
        destination: "LON",
        destinationName: "Londres",
        destinationLat: 51.5,
        destinationLong: -0.1,
        departureTime: "2025-07-08T10:00",
        arrivalTime: "2025-07-08T11:30",
        price: 95,
        duration: 90,
        company: "British Airways",
        distance: 344,
        tourismTypes: [4, 5],
        poi: [],
        badge: "gb",
      },
      {
        id: 9,
        origin: "LON",
        originName: "Londres",
        originLat: 51.5,
        originLong: -0.1,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-07-10T15:00",
        arrivalTime: "2025-07-10T17:00",
        price: 105,
        duration: 120,
        company: "Ryanair",
        distance: 1313,
        tourismTypes: [1, 2],
        poi: [],
        badge: "pt",
      },
      {
        id: 10,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "FNC",
        destinationName: "Funchal",
        destinationLat: 32.7,
        destinationLong: -16.8,
        departureTime: "2025-07-12T09:00",
        arrivalTime: "2025-07-12T11:00",
        price: 150,
        duration: 120,
        company: "TAP",
        distance: 1196,
        tourismTypes: [8],
        poi: [],
        badge: "pt",
      },
      {
        id: 11,
        origin: "AMS",
        originName: "Amsterdam",
        originLat: 52.4,
        originLong: 4.9,
        destination: "BER",
        destinationName: "Berlin",
        destinationLat: 52.5,
        destinationLong: 13.4,
        departureTime: "2025-07-11T10:00",
        arrivalTime: "2025-07-11T11:30",
        price: 100,
        duration: 90,
        company: "easyJet",
        distance: 359,
        poi: [
          {
            name: "Brandenburg Gate",
            latitude: 52.5,
            long: 13.4,
          },
        ],
        tourismTypes: [1, 5],
        badge: "nl",
      },
      {
        id: 12,
        origin: "BER",
        originName: "Berlim",
        originLat: 52.5,
        originLong: 13.4,
        destination: "PRG",
        destinationName: "Prague",
        destinationLat: 50.1,
        destinationLong: 14.4,
        departureTime: "2025-07-13T13:00",
        arrivalTime: "2025-07-13T14:15",
        price: 70,
        duration: 75,
        company: "Eurowings",
        distance: 175,
        poi: [
          {
            name: "Charles Bridge",
            latitude: 50.1,
            long: 14.4,
          },
        ],
        tourismTypes: [1, 3],
        badge: "cz",
      },
      {
        id: 13,
        origin: "PRG",
        originName: "Praga",
        originLat: 50.1,
        originLong: 14.4,
        destination: "VIE",
        destinationName: "Vienna",
        destinationLat: 48.2,
        destinationLong: 16.4,
        departureTime: "2025-07-15T15:00",
        arrivalTime: "2025-07-15T16:10",
        price: 60,
        duration: 70,
        company: "Austrian Airlines",
        distance: 158,
        poi: [
          {
            name: "Schönbrunn Palace",
            latitude: 48.2,
            long: 16.4,
          },
        ],
        tourismTypes: [3, 4],
        badge: "it",
      },

      {
        id: 14,
        origin: "VIE",
        originName: "Vienna",
        originLat: 48.2,
        originLong: 16.4,
        destination: "ZRH",
        destinationName: "Zurich",
        destinationLat: 47.4,
        destinationLong: 8.5,
        departureTime: "2025-07-17T17:00",
        arrivalTime: "2025-07-17T18:30",
        price: 95,
        duration: 90,
        company: "Swiss",
        distance: 383,
        poi: [
          {
            name: "Lake Zurich",
            latitude: 47.4,
            long: 8.5,
          },
        ],
        tourismTypes: [4, 7],
        badge: "ch",
      },
      {
        id: 15,
        origin: "ZRH",
        originName: "Zurique",
        originLat: 47.4,
        originLong: 8.5,
        destination: "MUC",
        destinationName: "Munich",
        destinationLat: 48.1,
        destinationLong: 11.6,
        departureTime: "2025-07-19T20:00",
        arrivalTime: "2025-07-19T21:10",
        price: 85,
        duration: 70,
        company: "Lufthansa",
        distance: 196,
        poi: [
          {
            name: "Marienplatz",
            latitude: 48.1,
            long: 11.6,
          },
        ],
        tourismTypes: [1, 4],
        badge: "de",
      },
      {
        id: 16,
        origin: "MUC",
        originName: "Munique",
        originLat: 48.1,
        originLong: 11.6,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-07-21T09:00",
        arrivalTime: "2025-07-21T11:00",
        price: 120,
        duration: 120,
        company: "TAP",
        distance: 1350,
        poi: [
          {
            name: "Ribeira",
            latitude: 41.2,
            long: -8.6,
          },
        ],
        tourismTypes: [3],
        badge: "pt",
      },
      {
        id: 17,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "FAO",
        destinationName: "Faro",
        destinationLat: 37.0,
        destinationLong: -7.9,
        departureTime: "2025-07-18T13:00",
        arrivalTime: "2025-07-18T14:00",
        price: 60,
        duration: 60,
        company: "TAP",
        distance: 288,
        poi: [
          {
            name: "Praia de Faro",
            latitude: 37.0,
            long: -7.9,
          },
        ],
        tourismTypes: [2, 8],
        badge: "pt",
      },
      {
        id: 18,
        origin: "FAO",
        originName: "Faro",
        originLat: 37.0,
        originLong: -7.9,
        destination: "LIS",
        destinationName: "Lisboa",
        destinationLat: 38.7,
        destinationLong: -9.1,
        departureTime: "2025-07-20T15:00",
        arrivalTime: "2025-07-20T16:00",
        price: 70,
        duration: 60,
        company: "Ryanair",
        distance: 173,
        poi: [],
        tourismTypes: [],
        badge: "pt",
      },
      {
        id: 19,
        origin: "LIS",
        originName: "Lisboa",
        originLat: 38.7,
        originLong: -9.1,
        destination: "DUB",
        destinationName: "Dublin",
        destinationLat: 53.3,
        destinationLong: -6.2,
        departureTime: "2025-07-22T08:00",
        arrivalTime: "2025-07-22T10:30",
        price: 140,
        duration: 150,
        company: "Aer Lingus",
        distance: 1015,
        poi: [
          {
            name: "Trinity College",
            latitude: 53.3,
            long: -6.2,
          },
        ],
        tourismTypes: [1, 3],
        badge: "IE",
      },
      {
        id: 20,
        origin: "DUB",
        originName: "Dublin",
        originLat: 53.3,
        originLong: -6.2,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-07-24T12:00",
        arrivalTime: "2025-07-24T14:00",
        price: 150,
        duration: 120,
        company: "Ryanair",
        distance: 1135,
        poi: [],
        tourismTypes: [1],
        badge: "pt",
      },
      {
        id: 21,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "AMS",
        destinationName: "Amsterdão",
        destinationLat: 52.4,
        destinationLong: 4.9,
        departureTime: "2025-07-25T07:00",
        arrivalTime: "2025-07-25T10:00",
        price: 100,
        duration: 180,
        company: "Transavia",
        distance: 1600,
        tourismTypes: [1, 4],
        poi: [],
        badge: "nl",
      },
      {
        id: 22,
        origin: "AMS",
        originName: "Amsterdão",
        originLat: 52.4,
        originLong: 4.9,
        destination: "OSL",
        destinationName: "Oslo",
        destinationLat: 59.9,
        destinationLong: 10.8,
        departureTime: "2025-07-27T13:00",
        arrivalTime: "2025-07-27T15:30",
        price: 130,
        duration: 150,
        company: "Norwegian",
        distance: 960,
        tourismTypes: [1, 7],
        poi: [],
        badge: "no",
      },
      {
        id: 23,
        origin: "OSL",
        originName: "Oslo",
        originLat: 59.9,
        originLong: 10.8,
        destination: "HEL",
        destinationName: "Helsínquia",
        destinationLat: 60.2,
        destinationLong: 24.9,
        departureTime: "2025-07-29T09:00",
        arrivalTime: "2025-07-29T12:00",
        price: 140,
        duration: 180,
        company: "Finnair",
        distance: 780,
        tourismTypes: [6, 7],
        poi: [],
        badge: "fi",
      },
      {
        id: 24,
        origin: "HEL",
        originName: "Helsínquia",
        originLat: 60.2,
        originLong: 24.9,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-07-31T10:00",
        arrivalTime: "2025-07-31T13:30",
        price: 160,
        duration: 210,
        company: "TAP",
        distance: 2850,
        tourismTypes: [4],
        poi: [],
        badge: "fi",
      },
      {
        id: 25,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "MIL",
        destinationName: "Milão",
        destinationLat: 45.4,
        destinationLong: 9.2,
        departureTime: "2025-08-01T08:00",
        arrivalTime: "2025-08-01T11:00",
        price: 110,
        duration: 180,
        company: "ITA Airways",
        distance: 1450,
        tourismTypes: [4, 6],
        poi: [],
        badge: "it",
      },
      {
        id: 26,
        origin: "MIL",
        originName: "Milão",
        originLat: 45.4,
        destinationLong: 9.2,
        destination: "VEN",
        destinationName: "Veneza",
        destinationLat: 45.5,
        destinationLong: 12.3,
        departureTime: "2025-08-03T14:00",
        arrivalTime: "2025-08-03T15:00",
        price: 80,
        duration: 60,
        company: "Alitalia",
        distance: 245,
        tourismTypes: [5, 6],
        poi: [
          {
            name: "St. Mark's Square",
            latitude: 45.5,
            long: 12.3,
          },
        ],
        badge: "it",
      },
      {
        id: 27,
        origin: "VEN",
        originName: "Veneza",
        originLat: 45.5,
        originLong: 12.3,
        destination: "FLR",
        destinationName: "Florença",
        destinationLat: 43.8,
        destinationLong: 11.2,
        departureTime: "2025-08-05T10:00",
        arrivalTime: "2025-08-05T11:00",
        price: 70,
        duration: 60,
        company: "Vueling",
        distance: 205,
        tourismTypes: [5, 6],
        poi: [],
        badge: "it",
      },
      {
        id: 28,
        origin: "FLR",
        originName: "Florença",
        originLat: 43.8,
        originLong: 11.2,
        destination: "NAP",
        destinationName: "Nápoles",
        destinationLat: 40.8,
        destinationLong: 14.3,
        departureTime: "2025-08-07T16:00",
        arrivalTime: "2025-08-07T17:00",
        price: 75,
        duration: 60,
        company: "ITA Airways",
        distance: 295,
        tourismTypes: [2, 4],
        poi: [],
        badge: "it",
      },
      {
        id: 29,
        origin: "NAP",
        originName: "Nápoles",
        originLat: 40.8,
        originLong: 14.3,
        destination: "PAL",
        destinationName: "Palermo",
        destinationLat: 38.1,
        destinationLong: 13.4,
        departureTime: "2025-08-09T12:00",
        arrivalTime: "2025-08-09T13:30",
        price: 85,
        duration: 90,
        company: "Alitalia",
        distance: 305,
        tourismTypes: [2, 4],
        poi: [],
        badge: "it",
      },
      {
        id: 30,
        origin: "PAL",
        originName: "Palermo",
        originLat: 38.1,
        originLong: 13.4,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-08-11T15:00",
        arrivalTime: "2025-08-11T17:30",
        price: 145,
        duration: 150,
        company: "TAP",
        distance: 1380,
        tourismTypes: [],
        poi: [],
        badge: "pt",
      },
      {
        id: 31,
        origin: "OPO",
        originName: "Porto",
        originLat: 41.2,
        originLong: -8.6,
        destination: "WAR",
        destinationName: "Varsóvia",
        destinationLat: 52.2,
        destinationLong: 21.0,
        departureTime: "2025-08-02T11:00",
        arrivalTime: "2025-08-02T15:00",
        price: 130,
        duration: 240,
        company: "LOT",
        distance: 2100,
        tourismTypes: [1, 5],
        poi: [],
        badge: "pl",
      },
      {
        id: 32,
        origin: "WAR",
        originName: "Varsóvia",
        originLat: 52.2,
        originLong: 21.0,
        destination: "BUD",
        destinationName: "Budapeste",
        destinationLat: 47.5,
        destinationLong: 19.0,
        departureTime: "2025-08-04T13:00",
        arrivalTime: "2025-08-04T14:30",
        price: 90,
        duration: 90,
        company: "Wizz Air",
        distance: 395,
        tourismTypes: [3, 4],
        poi: [],
        badge: "hu",
      },
      {
        id: 33,
        origin: "BUD",
        originName: "Budapeste",
        originLat: 47.5,
        originLong: 19.0,
        destination: "BUC",
        destinationName: "Bucareste",
        destinationLat: 44.4,
        destinationLong: 26.1,
        departureTime: "2025-08-06T16:00",
        arrivalTime: "2025-08-06T17:30",
        price: 80,
        duration: 90,
        company: "TAROM",
        distance: 395,
        tourismTypes: [5, 6],
        poi: [],
        badge: "ro",
      },
      {
        id: 34,
        origin: "BUC",
        originName: "Bucareste",
        originLat: 44.4,
        originLong: 26.1,
        destination: "SOF",
        destinationName: "Sofia",
        destinationLat: 42.7,
        destinationLong: 23.3,
        departureTime: "2025-08-08T09:00",
        arrivalTime: "2025-08-08T10:00",
        price: 65,
        duration: 60,
        company: "Bulgaria Air",
        distance: 180,
        tourismTypes: [3, 5],
        poi: [],
        badge: "hu",
      },
      {
        id: 35,
        origin: "SOF",
        originName: "Sofia",
        originLat: 42.7,
        originLong: 23.3,
        destination: "OPO",
        destinationName: "Porto",
        destinationLat: 41.2,
        destinationLong: -8.6,
        departureTime: "2025-08-10T14:00",
        arrivalTime: "2025-08-10T17:00",
        price: 155,
        duration: 180,
        company: "TAP",
        distance: 1750,
        tourismTypes: [],
        poi: [],
        badge: "pt",
      },
      {
        id: 36,
        origin: "OSL",
        originName: "Oslo",
        originLat: 59.9,
        originLong: 10.8,
        destination: "STO",
        destinationName: "Estocolmo",
        destinationLat: 59.3,
        destinationLong: 18.1,
        departureTime: "2025-08-03T10:00",
        arrivalTime: "2025-08-03T11:00",
        price: 90,
        duration: 60,
        company: "SAS",
        distance: 305,
        tourismTypes: [6, 7],
        poi: [],
        badge: "se",
      },
      {
        id: 37,
        origin: "STO",
        originName: "Estocolmo",
        originLat: 59.3,
        originLong: 18.1,
        destination: "CPH",
        destinationName: "Copenhaga",
        destinationLat: 55.6,
        destinationLong: 12.6,
        departureTime: "2025-08-05T15:00",
        arrivalTime: "2025-08-05T16:30",
        price: 85,
        duration: 90,
        company: "SAS",
        distance: 330,
        tourismTypes: [4, 6],
        poi: [],
        badge: "dk",
      },
    ];

    localStorage.setItem("flights", JSON.stringify(flights));
    console.log("Flights initialized");
  }

  // TRIPS
  if (!localStorage.trips) {
    const trips = [
      {
        id: 1,
        name: "Grand Tour Europeu",
        typesOfTourism: [1, 3, 4], // Aventura, Religioso, Gastronómico
        price: 1250,
        startDate: "2025-07-01",
        endDate: "2025-07-12",
        isPack: true,
        flights: [1, 3, 5, 6, 7], // OPO→LIS→BCN→ROM→ATH→IST
        miles: 4320,
      },
      {
        id: 2,
        name: "Europa Central Clássica",
        typesOfTourism: [1, 3, 4],
        price: 980,
        startDate: "2025-07-03",
        endDate: "2025-07-10",
        isPack: true,
        flights: [8, 9, 10, 11, 12, 13], // OPO→CDG→LHR→AMS→BER→PRG→VIE
        miles: 5430,
      },
      {
        id: 3,
        name: "Alpes e Baviera",
        typesOfTourism: [1, 4],
        price: 450,
        startDate: "2025-07-04",
        endDate: "2025-07-08",
        isPack: false,
        flights: [14, 15, 16],
        miles: 2310,
      },
      {
        id: 4,
        name: "Portugal Completo",
        typesOfTourism: [2, 3, 4], // Praia, Religioso, Gastronómico
        price: 280,
        startDate: "2025-07-05",
        endDate: "2025-07-08",
        isPack: true,
        flights: [17, 18],
        miles: 300,
      },
      {
        id: 5,
        name: "Escapadinha Irlandesa",
        typesOfTourism: [1, 3],
        price: 420,
        startDate: "2025-07-06",
        endDate: "2025-07-08",
        isPack: true,
        flights: [19, 20],
        miles: 900,
      },
      {
        id: 6,
        name: "Rota Mediterrânica",
        typesOfTourism: [2, 4],
        price: 265,
        startDate: "2025-07-01",
        endDate: "2025-07-03",
        isPack: false,
        flights: [2, 4],
        miles: 700,
      },
      {
        id: 7,
        name: "Capitais Imperiais",
        typesOfTourism: [1, 3],
        price: 360,
        startDate: "2025-07-01",
        endDate: "2025-07-05",
        isPack: true,
        flights: [5, 6, 7], // BCN→ROM→ATH→IST
        miles: 1540,
      },
      {
        id: 8,
        name: "Norte Europeu",
        typesOfTourism: [1, 3],
        price: 295,
        startDate: "2025-07-03",
        endDate: "2025-07-06",
        isPack: true,
        flights: [9, 10, 11],
        miles: 1675,
      },
    ];

    localStorage.setItem("trips", JSON.stringify(trips));
    console.log("Realistic travel packages initialized");
  }
}
